const fetch = require('node-fetch');

const feedsToImport = [
  { title: '医疗器械商业评论', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3887517830.atom' },
  { title: '林掌柜', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3081822577.atom' },
  { title: '口腔观察', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3206082720.atom' },
  { title: '赛柏蓝', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_2395083762.atom' },
  { title: '诊锁界', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3295282793.atom' },
  { title: '松柏群英会', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3873244016.atom' },
  { title: '思宇MedTech', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3221733998.atom' },
  { title: 'IVD从业者网', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3906159373.atom' },
  { title: '梅苗苗口腔', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3939195539.atom' },
  { title: 'Envista盈纬达', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_2399345724.atom' },
  { title: '齿学堂', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3938172141.atom' },
  { title: '爱齐科技', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3595562847.atom' },
  { title: '松佰牙科', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3221898731.atom' },
  { title: '看医界', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3074044114.atom' },
  { title: '高峰医疗DENFAC', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3008668191.atom' },
  { title: '亿欧网', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3095250124.atom' },
  { title: '彩立方数字化导航', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3070152811.atom' },
  { title: '三六九猎头', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3559070655.atom' },
  { title: '中国医疗器械行业协会', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3249042177.atom' },
  { title: 'e看牙口腔观察', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3272058164.atom' },
  { title: 'IPO早知道', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3947259277.atom' },
  { title: '赛柏蓝器械', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3071208771.atom' },
  { title: '励齿资讯推送', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3207026284.atom' },
  { title: 'Aha口腔工作室', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3597144055.atom' },
  { title: '健康界', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_2397538732.atom' },
  { title: 'ClubD', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3862640150.atom' },
  { title: '动脉橙产业智库', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3207261612.atom' },
  { title: '铼赛数字化齿科', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3003838271.atom' },
  { title: 'CIRS医械合规动态', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3282062656.atom' },
  { title: 'BITC种植大平台', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3514184205.atom' },
  { title: '爱迪牙', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3001465571.atom' },
  { title: '牙医管家', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3014082021.atom' },
  { title: '正丽科技', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3248651753.atom' },
  { title: '松禾资本', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3006123560.atom' },
  { title: 'FUSSEN菲森', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3078622019.atom' },
  { title: '药械网', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3009192529.atom' },
  { title: 'IT桔子', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_2392467062.atom' },
  { title: '美牙视界', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3907170289.atom' },
  { title: 'eBrace官方', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_2390163929.atom' },
  { title: '中国医学论坛报今日口腔', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3088072607.atom' },
  { title: '国家发展改革委', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3070196162.atom' },
  { title: 'DENALL口腔医学', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3939103136.atom' },
  { title: '中华口腔医学会', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_2399927761.atom' },
  { title: '医学界智库', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_2390424172.atom' },
  { title: 'MedTalent医人才', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3948691547.atom' },
  { title: '魔术牙医', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3084798734.atom' },
  { title: 'Aidite官方', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3277812495.atom' },
  { title: '投资界', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3298956650.atom' },
  { title: '柳叶刀机器人', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3918285524.atom' },
  { title: 'MedTrend医趋势', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3079622941.atom' },
  { title: 'Dr Clear可丽尔科技', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3235602429.atom' },
  { title: '中国药闻', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3073841657.atom' },
  { title: '口腔界网', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3927218641.atom' },
  { title: '牙研所', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3220404366.atom' },
  { title: 'TopKlout克劳锐', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3214099824.atom' },
  { title: '汉邦激光3D打印', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3074273658.atom' },
  { title: '茄子口腔医学', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3281025673.atom' },
  { title: '器械之家', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3875734843.atom' },
  { title: '牙牙在线', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3222959665.atom' },
  { title: '乐普乐齐', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3286222611.atom' },
  { title: '泰山 I 康盛亲水种植体', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3524068480.atom' },
  { title: '三六九医彩网', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3910298109.atom' },
  { title: '医涯学识', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3294057776.atom' },
  { title: '深圳云甲科技', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3290041718.atom' },
  { title: '倍康美数字口腔', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3278075136.atom' },
  { title: '欧欧球托舒适化矫正', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3540414551.atom' },
  { title: '时代天使', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_2399182523.atom' },
  { title: '医管界', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3079774517.atom' },
  { title: 'Align Technology News Releases', url: 'https://investor.aligntech.com/rss/news-releases.xml' },
  { title: '医学科研情报圈', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3884833461.atom' },
  { title: '业界新闻 – 中华口腔医学会', url: 'https://www.cndent.com/archives/category/%e5%8f%a3%e8%85%94%e8%b5%84%e8%ae%af/%e4%b8%9a%e7%95%8c%e6%96%b0%e9%97%bb/feed' },
  { title: 'Oral and Maxillofacial Surgery Clinics', url: 'http://www.oralmaxsurgery.theclinics.com/current.rss' },
  { title: 'Marty Jablow DMD, Dental News and Technology', url: 'http://dentechblog.blogspot.com/feeds/posts/default' },
  { title: 'Dentistry Today', url: 'https://www.dentistrytoday.com/feed/' },
  { title: 'Oral Health Group', url: 'http://www.oralhealthgroup.com/rssfeeds/OH_dailynews.xml' },
  { title: 'Dental Lab Network', url: 'http://dentallabnetwork.com/forums/forums/-/index.rss' },
  { title: 'Oral Surgery, Oral Medicine, Oral Pathology and Oral Radiology', url: 'http://www.oooojournal.net/current.rss' },
  { title: 'JCDA - Published by the Canadian Dental Association', url: 'http://www.jcda.ca/rss_2.0/' },
  { title: '"dental industry dentist 口腔 牙科 口腔行业 口腔产业 牙医" - Google 新闻', url: 'https://news.google.com/rss/search?hl=zh-CN&gl=CN&ceid=CN:zh-Hans&q=dental+industry++dentist+%E5%8F%A3%E8%85%94+%E7%89%99%E7%A7%91+%E5%8F%A3%E8%85%94%E4%BA%A7%E4%B8%9A+%E7%89%99%E5%8C%BB' },
  { title: 'School of Dentistry', url: 'http://dentistry.ucsf.edu/rss.xml' },
  { title: '"dentistry" - Google 新闻', url: 'https://news.google.com/rss/search?hl=zh-CN&gl=CN&ceid=CN:zh-Hans&q=dentistry' },
  { title: 'ADA News RSS', url: 'http://www.ada.org/en/ada-news-rss' },
  { title: 'Oral Health Foundation', url: 'https://www.dentalhealth.org/handlers/rss.ashx?feed=1' },
  { title: 'Wiley: Community Dentistry and Oral Epidemiology: Table of Contents', url: 'http://onlinelibrary.wiley.com/rss/journal/10.1111/(ISSN)1600-0528' },
  { title: 'JuniorDentist.com', url: 'http://www.juniordentist.com/feed' },
  { title: 'Wiley: Journal of Clinical Periodontology: Table of Contents', url: 'http://onlinelibrary.wiley.com/rss/journal/10.1111/(ISSN)1600-051X' },
  { title: 'Home | DrBicuspid.com', url: 'http://www.drbicuspid.com/rss/rss.aspx' },
  { title: 'European Journal of Orthodontics Advance Access', url: 'http://ejo.oxfordjournals.org/rss/ahead.xml' },
  { title: 'American Journal of Orthodontics and Dentofacial Orthopedics', url: 'http://www.ajodo.org/current.rss' },
  { title: 'Heartland Dental Blog', url: 'https://blog.heartland.com/rss.xml' },
  { title: 'Wiley: Australian Dental Journal: Table of Contents', url: 'http://onlinelibrary.wiley.com/rss/journal/10.1111/(ISSN)1834-7819' },
  { title: 'Provident Healthcare Partners', url: 'https://www.providenthp.com/feed/' },
  { title: 'ScienceDirect Publication: Journal of Dentistry', url: 'http://rss.sciencedirect.com/publication/science/03005712' },
  { title: 'Dental Clinics', url: 'http://www.dental.theclinics.com/current.rss' },
  { title: 'Wiley: International Endodontic Journal: Table of Contents', url: 'http://onlinelibrary.wiley.com/rss/journal/10.1111/(ISSN)1365-2591' },
  { title: 'John Flucke\'s Blog - Ramblings from Dentistry\'s Technology Evangelist', url: 'http://feeds.feedburner.com/dentaltechnologyblog1' },
  { title: 'Dentistry News -- ScienceDaily', url: 'http://www.sciencedaily.com/rss/health_medicine/dentistry.xml' },
  { title: 'Most Recent Articles: Progress in Orthodontics', url: 'http://www.progressinorthodontics.com/latest/rss' },
  { title: 'American Association of Dental Office Management', url: 'https://www.dentalmanagers.com/feed/' },
  { title: '"口腔行业" - Google 新闻', url: 'https://news.google.com/rss/search?hl=zh-CN&gl=CN&ceid=CN:zh-Hans&q=%E5%8F%A3%E8%85%94%E8%A1%8C%E4%B8%9A' },
  { title: 'International Journal of Oral Science', url: 'http://feeds.nature.com/ijos/rss/current' },
  { title: 'Becker\'s Dental Review - DSO + Dental News', url: 'https://www.beckersdental.com/?format=feed&type=rss' },
  { title: 'International Journal of Oral and Maxillofacial Surgery', url: 'http://www.ijoms.com/current.rss' },
  { title: 'Ask Dr. Spindel', url: 'http://lspindelnycdds.blogspot.com/feeds/posts/default' },
  { title: 'Journal of Endodontics', url: 'http://www.jendodon.com/current.rss' },
  { title: 'Dentistry news', url: 'http://medicalxpress.com/rss-feed/dentistry-news/' },
  { title: 'Group Dentistry Now', url: 'https://www.groupdentistrynow.com/feed/' },
  { title: 'The Journal of Prosthetic Dentistry', url: 'http://www.thejpd.org/current.rss' },
  { title: 'British Dental Journal', url: 'http://www.nature.com/bdj/current_issue/rss/' },
  { title: 'Dental Products Report articles', url: 'http://www.dentalproductsreport.com/rss' },
  { title: 'British Journal of Oral and Maxillofacial Surgery', url: 'http://www.bjoms.com/current.rss' },
  { title: '"牙科" - Google Noticias', url: 'https://news.google.com/rss/search?hl=es-419&gl=US&ceid=US:es-419&q=%E7%89%99%E7%A7%91' },
  { title: 'Evidence-Based Dentistry', url: 'http://www.nature.com/ebd/current_issue/rss/' },
  { title: 'Dentistry.co.uk', url: 'http://www.dentistry.co.uk/feed/newsfeed.xml' },
  { title: 'Align Technology News Releases', url: 'http://investor.aligntech.com/rss/news-releases.xml' },
  { title: 'FDI World Dental Federation Press Releases', url: 'https://feedproxy.feedly.com/56f38d72-26c1-4656-a993-91da31766e6c' },
  { title: 'Off the Cusp', url: 'http://feeds.feedburner.com/OffTheCusp' },
  { title: 'The Journal of the American Dental Association', url: 'http://jada.ada.org/current.rss' },
  { title: 'Most Recent Articles: BMC Oral Health', url: 'http://www.biomedcentral.com/bmcoralhealth/latest/rss' },
  { title: '"口腔" - Google Noticias', url: 'https://news.google.com/rss/search?hl=es-419&gl=US&ceid=US:es-419&q=%E5%8F%A3%E8%85%94' },
  { title: '"oral health" - Google News', url: 'http://news.google.com/news?hl=en&gl=us&q=oral%20health&um=1&ie=UTF-8&output=rss' },
  { title: 'SAGE Publications Inc: Journal of Dental Research: Table of Contents', url: 'http://journals.sagepub.com/action/showFeed?ui=0&mi=ehikzz&ai=2b4&jc=jdrb&type=etoc&feed=rss' },
  { title: '"dentist" - Google News', url: 'http://news.google.com/news?hl=en&gl=us&q=dentist&um=1&ie=UTF-8&output=rss' },
  { title: 'MDPM Dental Marketing', url: 'http://moderndentalmarketing.com/feed/' },
  { title: 'Journal of Oral and Maxillofacial Surgery', url: 'http://www.joms.org/current.rss' },
  { title: 'Dentistry - National Elf Service', url: 'http://www.thedentalelf.net/feed/' },
  { title: '"dental industry dentist 口腔 牙科" - Google 新闻', url: 'https://news.google.com/rss/search?hl=zh-CN&gl=CN&ceid=CN:zh-Hans&q=dental+industry+dentist+%E5%8F%A3%E8%85%94+%E7%89%99%E7%A7%91' },
  { title: 'SHOFU松风', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3227486913.atom' },
  { title: '恒伦医疗', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3257112280.atom' },
  { title: '齿不择言', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3215102979.atom' },
  { title: '精美医疗', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3553386823.atom' },
  { title: 'FourSmile福斯曼', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3275206682.atom' },
  { title: '松柏群英会', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3873244016.atom' },
  { title: '倍康美数字医疗', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3269104845.atom' },
  { title: '现代牙科集团', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3911283648.atom' },
  { title: '豪孚迪', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3082081788.atom' },
  { title: '梅苗苗口腔', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3939195539.atom' },
  { title: '华光口腔', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3011025241.atom' },
  { title: '西格玛医学', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3569155165.atom' },
  { title: '爱齐科技', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3595562847.atom' },
  { title: 'DentalDirekt 迪瑞', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3520986557.atom' },
  { title: '高峰医疗DENFAC', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3008668191.atom' },
  { title: '美立刻隐形正畸', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3520644463.atom' },
  { title: '轻松牙医', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3270927471.atom' },
  { title: 'Smartee正雅隐形矫治', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3567950330.atom' },
  { title: 'DMG公司', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3550818889.atom' },
  { title: '啄木鸟Woodpecker', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3071196412.atom' },
  { title: 'Dental J', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3872522013.atom' },
  { title: '锐珂医疗', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3088855438.atom' },
  { title: 'Aha口腔工作室', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3597144055.atom' },
  { title: 'COXO宇森医疗', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_2394800111.atom' },
  { title: '健康界', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_2397538732.atom' },
  { title: 'IMD埃蒙迪', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3005427776.atom' },
  { title: '铼赛数字化齿科', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3003838271.atom' },
  { title: '朗朗口腔', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3234217691.atom' },
  { title: '义获嘉Ivoclar', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3883895965.atom' },
  { title: '欧欧医疗', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3246253257.atom' },
  { title: '丹斯登DENSTEN', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3917677917.atom' },
  { title: '佰傲口腔', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3924347541.atom' },
  { title: '爱迪牙', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3001465571.atom' },
  { title: '正丽科技', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3248651753.atom' },
  { title: 'FUSSEN菲森', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3078622019.atom' },
  { title: '美亚光电', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_2396072016.atom' },
  { title: '摩方精密', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3219501392.atom' },
  { title: '先临三维高精度3D视觉', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3098532657.atom' },
  { title: '黑格科技', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3903379300.atom' },
  { title: '瑞尔学堂 Arrail Institute', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3000987267.atom' },
  { title: '朗视仪器', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3075141723.atom' },
  { title: 'e看牙', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3216145436.atom' },
  { title: '科维奇KOVACS', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3584060843.atom' },
  { title: '博辉瑞进', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3270234846.atom' },
  { title: '铖联科技', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3585761061.atom' },
  { title: '迅实科技', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3081706109.atom' },
  { title: 'Aidite官方', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3277812495.atom' },
  { title: '普利生3D打印', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3073781261.atom' },
  { title: 'Purgo柏谷生物', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3865630174.atom' },
  { title: '八颗牙Eighteeth', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3585674749.atom' },
  { title: '汉斯夫HansFive', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3015626483.atom' },
  { title: 'Dr Clear可丽尔科技', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3235602429.atom' },
  { title: 'ZUMAX速迈医学', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3537066847.atom' },
  { title: '登士柏西诺德服务号', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3084617024.atom' },
  { title: '微创未来', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3019600035.atom' },
  { title: 'WARANTEC沃兰', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3942640048.atom' },
  { title: '乐普乐齐', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_3286222611.atom' },
  { title: '诺一迈尔', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_2397068698.atom' },
  { title: '奥齿泰', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_2397845781.atom' },
  { title: '时代天使', url: 'https://tuotuo.zeabur.app/feeds/MP_WXS_2399182523.atom' },
  { title: 'Dental Asia', url: 'https://dentalasia.net/feed/' },
  { title: 'News (English) - World Health Organization', url: 'https://www.who.int/rss-feeds/news-english.xml' },
  { title: 'News Archives - Dental Asia', url: 'https://dentalasia.net/category/news/feed/' },
  { title: 'Journal of Endodontics', url: 'http://www.jendodon.com/current.rss' },
  { title: 'Dentistry news', url: 'http://medicalxpress.com/rss-feed/dentistry-news/' },
  { title: 'Group Dentistry Now', url: 'https://www.groupdentistrynow.com/feed/' },
  { title: 'The Journal of Prosthetic Dentistry', url: 'http://www.thejpd.org/current.rss' },
  { title: 'British Dental Journal', url: 'http://www.nature.com/bdj/current_issue/rss/' },
  { title: 'Dental Products Report articles', url: 'http://www.dentalproductsreport.com/rss' },
  { title: 'British Journal of Oral and Maxillofacial Surgery', url: 'http://www.bjoms.com/current.rss' },
  { title: 'Evidence-Based Dentistry', url: 'http://www.nature.com/ebd/current_issue/rss/' },
  { title: 'Dentistry.co.uk', url: 'http://www.dentistry.co.uk/feed/newsfeed.xml' },
  { title: 'Align Technology News Releases', url: 'http://investor.aligntech.com/rss/news-releases.xml' },
  { title: 'Off the Cusp', url: 'http://feeds.feedburner.com/OffTheCusp' },
  { title: 'The Journal of the American Dental Association', url: 'http://jada.ada.org/current.rss' },
  { title: 'Most Recent Articles: BMC Oral Health', url: 'http://www.biomedcentral.com/bmcoralhealth/latest/rss' },
  { title: 'MDPM Dental Marketing', url: 'http://moderndentalmarketing.com/feed/' },
  { title: 'Journal of Oral and Maxillofacial Surgery', url: 'http://www.joms.org/current.rss' },
  { title: 'Dentistry - National Elf Service', url: 'http://www.thedentalelf.net/feed/' },
];

const API_BASE_URL = 'http://localhost:3003/api'; // Replace with your actual API URL if different

async function importFeeds() {
  let successCount = 0;
  let failCount = 0;

  for (const feed of feedsToImport) {
    // Filter out feedly.com links and non-RSS/Atom URLs
    if (feed.url.includes('feedly.com') || !feed.url.match(/\.(rss|xml|atom)$/i)) {
      console.log(`Skipping invalid or Feedly URL: ${feed.url}`);
      continue;
    }

    console.log(`Attempting to add feed: ${feed.title} - ${feed.url}`);
    try {
      const response = await fetch(`${API_BASE_URL}/feeds`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(feed),
      });

      if (response.ok) {
        console.log(`Successfully added feed: ${feed.title}`);
        successCount++;
      } else {
        const errorText = await response.text();
        console.error(`Failed to add feed ${feed.title} (${feed.url}): HTTP Status ${response.status} - ${errorText}`);
        failCount++;
      }
    } catch (error) {
      console.error(`Error adding feed ${feed.title} (${feed.url}):`, error);
      failCount++;
    }
    // Add a delay between requests to avoid hitting rate limits
    await new Promise(resolve => setTimeout(resolve, 1000)); // 1-second delay
  }

  console.log(`\nImport process finished.`);
  console.log(`Successfully imported: ${successCount} feeds.`);
  console.log(`Failed to import: ${failCount} feeds.`);
}

importFeeds(); 